name: plateshare
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^2.0.6
  google_fonts: ^4.0.4
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  bcrypt: ^1.1.3
  firebase_storage: ^11.1.2
  curved_navigation_bar: ^1.0.3
  like_button: ^2.0.5
  file_picker: ^5.3.0
  lottie: ^2.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true



