// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHGoQ6fxAl9svGOiM3g_wOi_5MvmpMo4',
    appId: '1:502452164005:web:773ac1b79b58520b96c44c',
    messagingSenderId: '502452164005',
    projectId: 'plateshare-tfg2023',
    authDomain: 'plateshare-tfg2023.firebaseapp.com',
    storageBucket: 'plateshare-tfg2023.appspot.com',
    measurementId: 'G-T85QLK5XDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9J2llU9XIybLzRGsMViJPjSmAk8zXxfM',
    appId: '1:502452164005:android:3a14afa7654614e096c44c',
    messagingSenderId: '502452164005',
    projectId: 'plateshare-tfg2023',
    storageBucket: 'plateshare-tfg2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4TVO_3VVWIMHcfW6DFDPC5oAUDszxIhs',
    appId: '1:502452164005:ios:43085bda0601742296c44c',
    messagingSenderId: '502452164005',
    projectId: 'plateshare-tfg2023',
    storageBucket: 'plateshare-tfg2023.appspot.com',
    iosClientId: '502452164005-b2laa08a1mc01v05cgo3pf8prt6msggu.apps.googleusercontent.com',
    iosBundleId: 'com.example.plateshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4TVO_3VVWIMHcfW6DFDPC5oAUDszxIhs',
    appId: '1:502452164005:ios:43085bda0601742296c44c',
    messagingSenderId: '502452164005',
    projectId: 'plateshare-tfg2023',
    storageBucket: 'plateshare-tfg2023.appspot.com',
    iosClientId: '502452164005-b2laa08a1mc01v05cgo3pf8prt6msggu.apps.googleusercontent.com',
    iosBundleId: 'com.example.plateshare',
  );
}
